#!/usr/bin/env bash
#
# Open the post-release housekeeping PR(s) for a PedPy release.
#
# For a MINOR/major release (vX.Y.0):
#   * PR into `main`     : citation (+version bump), minor changelog placeholder,
#                          SECURITY table, README BibTeX.
#   * create `rls-X.Y`   : from the release tag, then PR into it with citation
#                          (+version bump), *patch* changelog placeholder,
#                          SECURITY table, README BibTeX.
#
# For a PATCH release (vX.Y.Z, Z>0, cut from rls-X.Y):
#   * PR into `rls-X.Y`  : citation (+version bump) and *patch* changelog
#                          placeholder only.
#   * PR into `main`     : citation snapshot (no version bump) and README BibTeX
#                          only, so main's citation stays current.
#
# Required environment:
#   VERSION       released version without a leading "v", e.g. 1.5.0
#   RELEASE_TYPE  "minor" or "patch"
#   RLS_BRANCH    matching release branch, e.g. rls-1.5
#   RELEASE_TAG   the release tag, e.g. v1.5.0 (start point for a new rls branch)
#   ZENODO_DOI    e.g. 10.5281/zenodo.20511313
#   PUB_DATE      publication date, YYYY-MM-DD
# Requires: git, gh (authenticated via GH_TOKEN), python3 with `requests`.

set -euo pipefail

: "${VERSION:?}" "${RELEASE_TYPE:?}" "${RLS_BRANCH:?}" "${RELEASE_TAG:?}"
: "${ZENODO_DOI:?}" "${PUB_DATE:?}"

cd "$(git rev-parse --show-toplevel)"

# Author identity for the generated commits. Defaults to the GitHub Actions
# bot; the workflow overrides these with the pedpy-bot GitHub App identity.
git config user.name "${GIT_BOT_NAME:-github-actions[bot]}"
git config user.email "${GIT_BOT_EMAIL:-41898282+github-actions[bot]@users.noreply.github.com}"

COMMON_ARGS=(--version "$VERSION" --zenodo-doi "$ZENODO_DOI" --pub-date "$PUB_DATE")

# open_pr <base> <head> <title> <body> [prepare_release.py args...]
open_pr() {
  local base="$1" head="$2" title="$3" body="$4"
  shift 4

  git fetch --quiet origin "$base"
  git checkout --quiet -B "$head" "origin/$base"

  python3 scripts/prepare_release.py "${COMMON_ARGS[@]}" "$@"

  if git diff --quiet && git diff --cached --quiet; then
    echo "No changes for '$head' (base '$base'); skipping PR."
    return 0
  fi

  git add -A
  git commit --quiet -m "$title"
  git push --force-with-lease origin "$head"

  if gh pr view "$head" --json number >/dev/null 2>&1; then
    echo "PR from '$head' already open; updated its branch."
  else
    gh pr create --base "$base" --head "$head" --title "$title" --body "$body"
  fi
}

ensure_rls_branch() {
  if git ls-remote --exit-code --heads origin "$RLS_BRANCH" >/dev/null 2>&1; then
    echo "Release branch '$RLS_BRANCH' already exists."
  else
    echo "Creating release branch '$RLS_BRANCH' from '$RELEASE_TAG'."
    git fetch --quiet origin "refs/tags/$RELEASE_TAG:refs/tags/$RELEASE_TAG" || true
    git push origin "refs/tags/$RELEASE_TAG^{commit}:refs/heads/$RLS_BRANCH"
  fi
}

main_body="Automated post-release housekeeping for **v${VERSION}** on \`main\`.

Please review the changelog date and the citation details before merging.

_Generated by \`.github/workflows/prepare-next-release.yml\`._"

rls_body="Automated post-release housekeeping for **v${VERSION}** on \`${RLS_BRANCH}\`.

Please review the changelog date and the citation details before merging.

_Generated by \`.github/workflows/prepare-next-release.yml\`._"

if [ "$RELEASE_TYPE" = "minor" ]; then
  open_pr main "release-prep/v${VERSION}" \
    "Prepare next development cycle after v${VERSION}" "$main_body" \
    --citation --changelog minor --security --readme

  ensure_rls_branch
  open_pr "$RLS_BRANCH" "release-prep/${RLS_BRANCH}-after-v${VERSION}" \
    "Prepare ${RLS_BRANCH} after v${VERSION}" "$rls_body" \
    --citation --changelog patch --security --readme
else
  open_pr "$RLS_BRANCH" "release-prep/${RLS_BRANCH}-after-v${VERSION}" \
    "Prepare ${RLS_BRANCH} after v${VERSION}" "$rls_body" \
    --citation --changelog patch

  open_pr main "release-prep/citation-v${VERSION}" \
    "Add v${VERSION} citation snapshot" "$main_body" \
    --citation --no-citation-version-bump --readme
fi
